### PR TITLE
Some layout implementations

### PR DESCRIPTION
**Pull request by RLesur**
I've tried to update the main parts of the layout following the new design system.
Here's a screenshot 
_sspcloud

This is the first time I work with React: I'm not familiar with the styling best practices with this framework. 
I'm sure this PR can be improved.

### CODE REVIEW

**Comment by olevitt** [comment]
Nice, thx !

**Comment by garronej** [comment]
@RLesur @olevitt Nice. I will take it from here 👍

**Comment by garronej** [comment]
implem_design

@RLesur  @olevitt  I started the design implementation. Be sure it will be done by monday.

@RLesur Thanks for the `::after` that get the partial underline, nicely done 👍

**Comment by RLesur** [comment]
@garronej The highest priority is to take care of you!

I agree with you for the login button.

I have one regret for the partial underline. I think an absolute dimension should be used here:

https://github.com/InseeFrLab/onyxia-ui/blob/9dc85c75306603458e8dab8fe83f255c05d5912e/src/js/components/accueil/accueil.scss#L30

I will have some time on Sunday if you need some help.

**Pull request merged**
