### PR TITLE
Add verdant theme palette

### PR DESCRIPTION
**Pull request by tongyeouki**

### CODE REVIEW

**Comment by garronej** [comment]
Great thanks!  
It's nice to paste screenshots for this kind of PR but great, merging

**Comment by tongyeouki** [comment]
Light theme : 

image

Dark theme : 

image

Feel free to bring changes if necessary !

**Comment by garronej** [comment]
Noice!  
https://www.youtube.com/watch?v=h3uBr0CCm58

**Comment by garronej** [comment]
Please run `yarn format` then commit again.  
It usually run itselfs if you have ran `yarn install` in your workspace.

**Pull request merged**
